# Site Settings
title: "学术笔记 - 计算生物与密度泛函理论"
email: your-email@example.com
description: >-
  个人学术笔记网站，专注于计算生物学和密度泛函理论研究。
  记录学习心得、研究进展和技术分享。
baseurl: ""
url: "https://foranewlife.github.io"
twitter_username: your_twitter
github_username: foranewlife

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Math support
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Navigation
header_pages:
  - about.md
  - research.md
  - notes.md
  - cv.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - "*.md"